### ISSUE TITLE
Locally saved PDFs don't open in PDF.js

### ISSUE THREAD

**Issue by ghost** [qutebrowser/qutebrowser#1252]
Online PDFs open in PDF.js, but locally saved PDFs don't. QB just tries to download them.

**Comment by The-Compiler** [comment]
I can confirm this. This might be caused by the same thing #566 is, but I'm not sure. Maybe @Kingdread knows more?

**Comment by Kingdread** [comment]
Should be the same bug, I'm pretty sure. pdf.js is only triggered on mimetypes `application/pdf` and `application/x-pdf`, but local files don't have the mimetype header. Should be fixed when mime-sniffing is implemented.

**Comment by m2habert** [comment]
On the Mac OS it pipes to the default browser (as we can't, as of now, make QB the default one).

**Comment by lahwaacz** [comment]
#566 has been closed recently as QtWebEngine is doing the right thing for HTML, but PDFs still have the same issue...

**Comment by The-Compiler** [comment]
We could probably just use `QDesktopServices.openUrl` (i.e. `xdg-open`) when we detect a download for a `file://` url.

**Comment by The-Compiler** [comment]
We could at least look at the filename (with Python's [mimetype.guess_type](https://docs.python.org/3.6/library/mimetypes.html#mimetypes.guess_type)) when we don't have a `Content-Type` header in [`on_unsupported_content`](https://github.com/qutebrowser/qutebrowser/blob/v0.10.1/qutebrowser/browser/webkit/webpage.py#L250-L286).

I'd like to wait until there's QtWebEngine support for PDFJS first though.

**Comment by mollison** [comment]
"We could probably just use QDesktopServices.openUrl (i.e. xdg-open) when we detect a download for a file:// url. This won't help for the pdfjs case, but at least make more sense than the current behavior."

This would be a very useful feature for me. FYI, I'm not at all concerned about PDF.js or PDFs in particular. Just want to be able to open local files in the proper application automatically, without any kind of download prompt coming up.

**Comment by The-Compiler** [comment]
@mollison This is only about what happens with local files *after* pressing ctrl-x (with the exception of using pdfjs for PDFs). I'm not sure whether it's a good idea to add an option to automatically open downloads based on the mimetype, as it's probably a bad idea security-wise... But I need to think about it some more. I opened #3353 now.

**Comment by The-Compiler** [comment]
Works fine with QtWebEngine, and I'd rather not do mime sniffing at all.
