### ISSUE TITLE
:spawn  breaks erratically on OS X

### ISSUE THREAD

**Issue by m2habert** [qutebrowser/qutebrowser#2249]
[QB 0.8.4 under MacOS 10.11.2] 

Something breaks the passing of bash commands to the shell through :spawn in OSX. At some point as the faultage sets in all I get is "command exited" error messages.

The solution is to reset everything thru an OS account log out (QB restart do not help)

Because of that and error messages mentioning "/System/Library/Frameworks/Python.framework/Versions/2.x/bin/python" (failed to properly save them: will do next time) I think it may be caused by some mismatch between Python Versions... 

MacOS comes with 2.7 but I set 3.4 as the active through MacPorts ("port select --set python"). Everything seems to work fine otherwise: I mainly use :spawn to activate mpv and youtube-dl, as well as a simple bash script that copies QB's default session to a backup folder in case a crash wipes it out.

Most of the time it works glitchless for days (I've recently registered a 15 day no incident period), but once in a while something prompts the "breakage" to resurface in a matter of hours.

Obviously it wouldn't be that of a drag if logout + login  wasn't such a time consuming solution...

Maybe if we knew exactly what is going on one could perform a much faster and simple reset. (please bear in mind that my afore-mentioned hunch is totally based in a really weak knowledge of python and all)

**Comment by The-Compiler** [comment]
All `:spawn` does is spawning something through the OS, with no shell involved.

With so little information there's really nothing I can do - can you please do `:report` the next time this happens, and mention this issue in the report?

**Comment by The-Compiler** [comment]
Your reports show no `$PATH` being set at all. Can you do a report right after starting up (or just check if `$PATH` is in the environment variables there)?

**Comment by m2habert** [comment]
I don't follow... I was referring to the $PATH set in ~/.bash_profile... ¿Did you mean  another one?

¿Do you mean by "starting up" to refer to an OS restart? Because everything works perfect if so, no errors... If so, ¿do you want me to 1)restart 2)start QB + use :spawn 3)report right away?

(if by any chance you mean a shell start up, I can't start QB thru the shell command line, I get the same fatal error message as in #2219)

**Comment by The-Compiler** [comment]
I mean the same `$PATH` - the report tells me that no `$PATH` exists at all. I mean a report at the point where spawning still works.

**Comment by m2habert** [comment]
Done!
 I've restarted QB, "spawned" my script which is in the $PATH and sent report right away.

**Comment by The-Compiler** [comment]
Relevant reports:

- http://paste.the-compiler.org/view/b35caebe
- http://paste.the-compiler.org/view/af74a306
- http://paste.the-compiler.org/view/d2a1933f (working)

I don't see `$PATH` in any of those though, which is strange. I'd expect OS X to use `$PATH` outside of the shell as well?!

Can you please show the following both when it works and when it doesn't?

- The output of `:debug-pyeval __import__('os').environ['PATH']`
- Whether `:debug-pyeval __import__('subprocess').check_call(['¶qBackup'])` runs your script (qutebrowser will freeze during that, that's fine).

Also, does anything change if you use a script without `¶` in its name? In the report where it's working, your qutebrowser has `LC_CTYPE = UTF-8` set, while in the other cases it hasn't, so that might very well be the issue.

**Comment by m2habert** [comment]
Right now I can provide for the "when it works" case:

Output of ...environ[PATH] :

'/opt/local/bin:/opt/local/sbin:/opt/local/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/m2habert/¶bin:/Users/m2habert/Android/android-sdk-macosx/platform-tools:/Users/m2habert/Android/android-sdk-macosx/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/m2habert/.fzf/bin'



:debug_pyeval did NOT run my script, 
error output :

```
Traceback (most recent call last):
  File "qutebrowser/misc/utilcmds.py", line 195, in debug_pyeval
  File "<string>", line 1, in <module>
  File "subprocess.py", line 576, in check_call
  File "subprocess.py", line 557, in call
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1551, in _execute_child
OSError: [Errno 8] Exec format error
```


(I copied same script to a /usr/local/bin (also in $PATH) and renamed to "test", just in  case: the result was the same, same error output.
)


 About the use of '¶':      
  It doesn't seem so, cause the full path (/Users/m2habert/¶bin/¶qBackup) works fine, EVEN when :spawn fails with youtube-dl.

Also: both :spawn mpv  and :spawn youtube-dl fail, and they are both in /opt/local/bin 

 ...

We'll need to wait for the ":spaw not working" output, as it has been behaving nicely these days...

**Comment by m2habert** [comment]
:spawn finally(??) broke so I could run your enquirees:

output of ...eviron[PATH] :

`'/usr/bin:/bin:/usr/sbin:/sbin'

`
error output of :debug-pyeval __import__('subprocess').check_call(['¶qBackup']) :

seems to be the different on the last line: 

```
Traceback (most recent call last):
  File "qutebrowser/misc/utilcmds.py", line 195, in debug_pyeval
  File "<string>", line 1, in <module>
  File "subprocess.py", line 576, in check_call
  File "subprocess.py", line 557, in call
  File "subprocess.py", line 947, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '¶qBackup'

```

**Comment by The-Compiler** [comment]
So as you can see there, `/Users/m2habert/¶bin/` is not in your `$PATH` anymore, so it can't find that script. I have no idea why it isn't in the `$PATH` - qutebrowser doesn't modify `$PATH` anywhere.

I'm closing this for now as I don't think this is a qutebrowser issue, but I'm happy to help track this down anyways. Are you starting qutebrowser differently when it happens?

**Comment by m2habert** [comment]
No, nothing is different. It just breaks. And I've tried everything to restart QB in order to something "get fixed" to no avail. 

Right now the only fix is to restart the OS account : logout the re-login.

I'm aware that this probably is not a QB's issue exactly... but it certainly is notable to OS X users.

And I really do not need a totally perfect fix for the problem: if there was a way to reset / renew the proper ways of things that would be less cumbersome than the total OS restart, that would be good enough.

**Comment by The-Compiler** [comment]
I've not seen other OS X users having this issue :wink:

Where do you add that folder to the path?

**Comment by m2habert** [comment]
Maybe it happens to OS X users who use macports?

My folder path is not the main issue: the main thing is that /opt/local/bin (used by macports) also gets ignored, and so I loose mpv and youtube-dl... 

(because of their inner-workings it doesn' matter that I assign an absolute path to either of them: they break internally and I get error messages like 
```_Process stderr:
Traceback (most recent call last):
  File "/Users/usr_name/my_bin/umpv", line 91, in <module>
    subprocess.check_call(opts)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle_```

mentioned in #2015 


MacPorts adds /opt/local/bin to the PATH in .bash_profile

**Comment by The-Compiler** [comment]
Let's focus on one problem at the time. Where do you add `/Users/m2habert/¶bin` to the path? If it's in `.bash_profile`, I think it won't be in the path if you don't start qutebrowser from bash.

**Comment by m2habert** [comment]
Yeah, I use `~/.bash_profile` (as MacPorts for the `opt/local/bin/`)

**Comment by The-Compiler** [comment]
So do you start qutebrowser from bash? If not, I doubt this is going to work.

**Comment by m2habert** [comment]
No, I don't. I start qb from the OS. But it works... for days, then something breaks.

**Comment by m2habert** [comment]
( I can't start QB from bash command line, I get the same fatal error message as in #2219)

**Comment by m2habert** [comment]
¿Is there another way of setting PATH that would work across any situation?

**Comment by The-Compiler** [comment]
Maybe using `/etc/paths.d` or `/etc/launchd.conf`, see http://superuser.com/a/654010  - but I'm really no OS X expert.

**Comment by m2habert** [comment]
Thanks, I've found about the `/etc/paths` file as well.

But I had to log out then log back to make it work, so now the problem / error is gone and there's no way to check if it made a difference. 

So I'm back to waiting for `:spawn mpv {link}` to break again (or maybe a global $PATH was what was missing)...

**Comment by m2habert** [comment]
`:spawn`  stopped worked again and, despite my tinkering with `/etc/paths` and `/etc/launchd.conf`, `:debug-pyeval __import__('os').environ['PATH']` still returns:
` '/usr/bin:/bin:/usr/sbin:/sbin' `

:-(

**Comment by chaosbunker** [comment]
@m2habert from what I can tell you have to work with the absolute path when you launch qutebrowser.app

absolute paths are not necessary if you symlink the qutebrowser executable somewhere into your path, e.g. /usr/local/bin and launch it from the terminal

Save the follwing in `/usr/local/binqutebrowser`

```
#!/usr/bin/env bash

# Without nohup, the started process is still considered a "child" of the terminal process and thus terminated if the terminal is closed
nohup /Applications/qutebrowser.app/Contents/MacOS/qutebrowser >/dev/null 2>&1 & 
# sleep briefly, because iTerm...
sleep 2
exit
```

make it executable
`chmod +x /usr/local/bin/qutebrowser`

run from terminal and you can `:spawn mpv {url}`

It's a bit weird that as soon as you make this same script into an app :spawn does not work anymore :-/ Seems like apps know nothing about the $PATH

if you insist on launching it from the dock, rename `/usr/local/bin/qutebrowser` to `/usr/local/bin/qutebrowser.app` 

`mv /usr/local/bin/qutebrowser /usr/local/bin/qutebrowser.app`

and drag it into the dock. if you want to see the qutebrowser icon 'Get Info' for the real qutebrowser app, copy the icon and 'Get Info' your script and paste the icon. While you're there, make sure to open executables with your preferred terminal emulator / iTerm, what else:-P

When you're done, change the name back, launch from dock.

`mv /usr/local/bin/qutebrowser.app /usr/local/bin/qutebrowser`

Finally, curse apple for making your life so difficult -_-

**Comment by m2habert** [comment]
Thanks! Easy fix.

**Comment by The-Compiler** [comment]
@m2habert I saw your crash report - this is most likely already fixed in newer versions, v1.1.1 is old. In the future, please provide an email address instead of linking to an unrelated issue - I'm not going to comment here again and send some 160 people a mail for some random crash report :wink:

**Comment by m2habert** [comment]
Sorry, my bad.

**Comment by m2habert** [comment]
The problem still persists... I updated to v1.3.2 and :spawn broke instantly.  :-(

**Comment by 191205** [comment]
version 1.3.3, Mac os , having the same problem

**Comment by The-Compiler** [comment]
@191205 What problem exactly? This issue was about multiple problems at once, so without more information it's impossible to help you.

**Comment by m2habert** [comment]
I think @191205 means `:spawn` breaking when not using @chaosbunker 's fix. I'm stuck at v1.5.2 ( since Mac OS 10.11.6 user) and "spawn breakage" still happens if I launch qB from qutebrowser.app

**Comment by gerrywastaken** [comment]
For anybody else running into this. The only way I was able to set the environment PATHs so that qutebrowser picket them up was via the 

`sudo launchctl config user path <path>` command followed by a restart.

e.g.
`sudo launchctl config user path /User/myname/bin:/usr/local/bin:/otherrandompath/bin`

NOTHING else worked. Not /etc/paths or even this which is specificially about getting paths working in qutebrowser:
https://www.bounga.org/tips/2020/04/07/instructs-mac-os-gui-apps-about-path-environment-variable/
