### ISSUE TITLE
Loading issue?

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4208]
Is anyone else having issues while loading pages?

For the past couple of weeks, I have had to refresh many pages (sometimes several times) to have them fully load. If I don't, the loading process stops without having completed and I get no error message. This is something that I never noticed until rather recently and I do not experience if testing the same pages on another browser.

(Let me know if you need any info from my configuration).

Thank you

**Comment by NoctuaNivalis** [comment]
Can't say I've run into this myself. Is this related to some specific pages or does it just occur at random anywhere?

Maybe you could try to reproduce this with `--temp-basedir`, if it occurs often?

**Comment by prosoitos** [comment]
Seems to happen at random anywhere.

**Comment by The-Compiler** [comment]
What do you mean with "blue progress bar" exactly? The one in the statusbar isn't supposed to be blue, though it's possible that it is, depending on your theme.

Do you have a proxy set (see the `content.proxy` setting)?

Also, can you try quitting qutebrowser and removing `~/.cache/qutebrowser`? No important data should be stored in there, but maybe it helps clearing it.

**Comment by prosoitos** [comment]
The problem is still there. So it wasn't because of the cache...

**Comment by prosoitos** [comment]
I *might* have gotten a clue:

Usually, when the problem happens, the page is all white (then loads properly if I refresh) or it loads poorly with messed up formatting of some elements with most missing (and again, loads fine if I refresh). But upon vising a [superuser](https://superuser.com/) page, I got the error message:

`Super User requires external JavaScript from another domain, which is blocked or failed to load.`

which disappeared upon refreshing the page...

**Comment by R3load** [comment]
A similar, if not the same issue (random white page or broken formatting, fixed or semi-fixed by refresh) used to happen for my mom on a Samsung NP310-E5C with Windows 8 preinstalled, in Google Chrome. Could've been happening in Firefox too, not sure. Probably did though, as I can't remember a reason for her to be hellbent on using Chrome. She'd probably just start using FF and forget about it.
Pretty sure, because it was enough of a mystery, despite quite a bit of online searching, to convince her to switch to a Linux desktop. Which is unreal :D

The issue was reported on similar laptops with the same OS. Nobody I've read talking about it had a clue as to what it could've been.

*cue X-files theme* 😂

That Windows 8 install is (un)fortunately biting the dust in limbo, as the laptop now belongs to me. Good luck though ¯\\\_(ツ)\_/¯

**Comment by prosoitos** [comment]
![image](https://user-images.githubusercontent.com/4634851/45594120-0eb10200-b94a-11e8-87bb-ee747a5a27ae.png)

Here is the message I am talking about. And my problem is still there. Something is definitely not loading. Any suggestion would be great. Thanks!

**Comment by prosoitos** [comment]
Yet another message from a website that confirms that something doesn't load fast enough or gets blocked for some time in my system. While loading a website, I got this message:

![2018-09-23_15-16](https://user-images.githubusercontent.com/4634851/45933527-a4005780-bf43-11e8-85ef-8ab34bbe5010.png)

Yet, after clicking "OK", the page was loaded fine and I did not have to refresh the page for it to load properly as I have to do so often. Multiple tries give systematically the same result (and I do not get this from another browser).

The problem might not be caused by qutebrowser since nobody else seems to be having it and could be anything else in my settings. But I am still looking for a fix.

**Comment by prosoitos** [comment]
I noticed recently that I also could not access my browsing history anymore. A new tab would pop up with the header "Browsing history", but the rest of the page would be totally blank. So there was definitely something wrong going on with qutebrowser in my current computer environment.

But upgrading today from 1.4.2-1 to 1.4.2-2, for whatever reason, solved my browsing history page and *it seems* my page loading issue. If this is confirmed, I will close the issue in a day or two.

**Comment by jgkamat** [comment]
IIRC there was a bug in qt 5.11.2 which was pushed out to arch recently. There
is a fix for this in master, and (I think) that fix was in 1.4.2-2 in arch (but not in
an official qb release).

That explains the :history issue, but I have no idea why this would fix the
loading issue. Maybe that was fixed in qt 5.11.2

Marie-Helene Burle writes:

**Comment by prosoitos** [comment]
My loading issue seems to indeed be gone. I cannot recall whether it started after a qt or a qutebrowser update, but I suspect that it might have. In any event, it seems that today's update solved it. I haven't had to reload any page today and I don't get the error message on SO anymore.

There might not have been any link with the history issue and I am not certain that they started at the same time since I don't use the history that often. They both ended in the same update.

Anyway, since this now seems solved, I will close the issue.

**Comment by prosoitos** [comment]
Problem started again today. Amongst today's Arch Linux updates is `haskell-http`. But I have no clue whatsoever whether there is a link with it as this is entirely outside my expertise.

**Comment by prosoitos** [comment]
Problem started again today. Amongst today's Arch Linux updates is haskell-http. But I have no clue whatsoever whether there is a link with it as this is entirely outside my expertise.

**Comment by prosoitos** [comment]
Problem started again today. Amongst today's Arch Linux updates is haskell-http. But I have no clue whatsoever whether there is a link with it as this is entirely outside my expertise. I simply don't see what, in the other updates, might be linked at all.

**Comment by NoctuaNivalis** [comment]
`haskell-http` is just a collection of library files for haskell client side http. It'd be very wrong if that'd have something to do with qutebrowser.

**Comment by prosoitos** [comment]
OK. Thanks.

**Comment by prosoitos** [comment]
Problem stopped again (I did not change any config file, but I update Arch often) and I am back to a functional qutebrowser with one exception:

I get `HTTP ERROR 440` when trying to access my university's outlook website (https://mail.sfu.ca).

**Comment by NoctuaNivalis** [comment]
@prosoitos error after logging in? Once again, the page "just loads" for me; I can't login of course.

**Comment by prosoitos** [comment]
No, I couldn't even reach the page while I could in other browsers. Rebooting several times had no effect and it lasted 2 days. But I just tried it and now it works. So I will close this again.

Sorry this issue has been messy throughout and might have had nothing to do with qutebrowser...

**Comment by prosoitos** [comment]
I won't reopen this issue, but I, again, cannot access my university's outlook website at https://mail.sfu.ca (same `HTTP ERROR 440` as before. Been a few days). And I, again, have to refresh pages to load pages (no idea whether there is any link between the two though. And probably not).

Not a big deal. I use `mu`, so I seldom have to access emails from the web and I can do that in another browser. And I got used to having to refresh pages on a regular basis. But there is definitely something up with qutebrowser with my settings.

**Comment by The-Compiler** [comment]
FWIW officially, no HTTP 440 status exists - but apparently Microsoft's IIS webserver stuff uses it for "Login timeout".

According to [this article](https://support.microsoft.com/en-us/help/941201/error-message-when-you-try-to-log-on-to-exchange-2007-by-using-outlook), that seems to be a server-side issue:

> This issue occurs if a permissions issue or an authentication issue exists in Internet Information Services (IIS) or in the IIS metabase.

(Nevermind that 4xx is reserved for client-side errors and 5xx is for server-side errors - this is Microsoft after all, it's not like I'd expect them to follow common standards :laughing:)

**Comment by prosoitos** [comment]
But when that happens, I can access the site without problem with chromium...

**Comment by The-Compiler** [comment]
Maybe it's just some temporary failure? When it works fine with Chromium and you retry immediately with qutebrowser, is it still broken?

**Comment by prosoitos** [comment]
Yes. For instance, it has been broken for several days. But no problem with chromium and no problem getting my emails in and out of mu4e with offlineimap...

**Comment by The-Compiler** [comment]
Fun. No idea what's going on. #4259 also talks about some weird network issues, but other than that, I've never heard of any similar issues (and haven't had any myself, using Outlook Web from time to time as well).

**Comment by prosoitos** [comment]
mmm... weird.

As I said: not the end of the world since I do all my email stuff in mu4e and only very rarely access it directly from Outlook Web (to double check how something is rendered). And in those rare cases, I can use chromium. I keep chromium installed exactly for those rare events when something doesn't work in qutebrowser.

The problem loading pages is more tedious. Refreshing always does the trick, but at times, there is a lot of that required.

**Comment by prosoitos** [comment]
My problem is on-going and FWIW, I have a few more observations:

- sometimes loading simply does not work, even if I refresh. In those cases, I have to restart qutebrowser and then the pages open

- sometimes, I first get `ERR_NAME_NOT_RESOLVED`, refresh, I get poorly loaded page, refresh, finally get to the loaded page
