### ISSUE TITLE
Match color does not show up in completion

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#4519]
**Version info (see `:version`)**:
Broken:
- https://paste.the-compiler.org/view/13d147a2
- https://paste.the-compiler.org/view/afa000e3

Working:
- https://paste.the-compiler.org/view/fcd00119

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes

**Description**
I don't have enough time to debug this issue myself anymore so I'm filing an issue

On master, since switching to `QSyntaxHighlighter` on #4220, matches no longer show up for me on qt 5.11.3. qt 5.12 and 5.11.1 seems fine.

Breaking the SyntaxHighlighter so that it highlights everything does not help, so I think this is some issue we're triggering in qt...

Broken:
![2019-01-10-170110_358x61_scrot](https://user-images.githubusercontent.com/4349709/51006700-651aff80-153c-11e9-88e5-d727b8c24925.png)

Working:

![2019-01-10-170048_421x44_scrot](https://user-images.githubusercontent.com/4349709/51006707-69471d00-153c-11e9-897e-2cce67d7d410.png)

**How to reproduce**

type `:version` and expect a match.

**Comment by jgkamat** [comment]
I see this now in fedora 28 testing as well, they're currently pushing from 5.11.1->5.11.3:

Broken:
https://paste.the-compiler.org/view/9447e8d8

**Comment by The-Compiler** [comment]
Given that I currently don't use my laptop too much anyways (learning for exams), I'll spend some CPU cycles to bisecting this in Qt.

Also, cc @rcorre, though indeed this looks like something broken in Qt somehow.

**Comment by The-Compiler** [comment]
Reproduced with a Qt build on the current 5.11 branch. Trying 5.11.1 now, then I'll start bisecting.

**Comment by The-Compiler** [comment]
https://codereview.qt-project.org/#/c/244699/ is to blame: https://github.com/qt/qtbase/commit/dec7961709c90f6977d2447f7fa6c6625af41cb2

Now the more interesting question is why it works on 5.12...

**Comment by The-Compiler** [comment]
This commit didn't made it to 5.12.0, but it will be in 5.12.1.

**Comment by The-Compiler** [comment]
Likely fixed in Qt 5.12.2 here: https://codereview.qt-project.org/#/c/249881/ (thanks, @Morten242!). However I don't think 322b4d26d8b650340550871d0a1e5e75f817c63a has any negative impact, so I'd say let's just keep things as they are.

**Comment by Morten242** [comment]
Unfortunately that patch does not fix this issue in particular.

Although for some background to this issue; the previous behavior was

1.  Assigning a document containing text to `QSyntaxHighlighter` starts a delayed rehighlight
2. Updating the text of the document causes the delayed rehighlight to be cancelled, and then to highlight the new section of the document (the bug I initially fixed, but if you updated the entire document this was not noticeable)

With my patch the behavior is

1. Assign document containing text, starting delayed rehighlight
2. Any changes to the document would not be highlighted until the rehighlight (likely your issue), which happens once the application starts processing events again (which would probably need an update in the styled item delegate)

The patch you linked to fixes someone's complaint where they were manually calling 
`QSyntaxHighlighter::rehighlight()` but the delayed rehighlight would run again later, simply an oversight from my side.

The PR here works (and would also be working correctly previously) because previously it would simply ignore any delayed rehighlight and highlight new section when the text is updated, and currently it works because it will highlight immediately since the initial document was empty (and as such no delayed rehighlight started).

Once again, sorry for causing the breakage; I hadn't considered the use-case where the widget would be drawn before the highlight even was processed. And sorry for the long post! It got a lot longer and more wordy than I intended...

**Comment by The-Compiler** [comment]
> Once again, sorry for causing the breakage; I hadn't considered the use-case where the widget would be drawn before the highlight even was processed.

No worries! I've seen far worse breakage with QtWebEngine updates :wink:

> And sorry for the long post! It got a lot longer and more wordy than I intended...

I definitely prefer long posts over the opposite - I've worked on open-source projects with people where you always get one-sentence (if you're lucky) responses and need to ask over and over again what they actually meant :wink:
