### ISSUE TITLE
pdfjs no longer working on downloaded files

### ISSUE THREAD

**Issue by n8xm** [qutebrowser/qutebrowser#4612]
**Version info (see `:version`)**: 1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): Yes

**Description**
Opening a downloaded PDF using pdfjs fails, even though pdfjs appears to be functional ([this test file](https://mozilla.github.io/pdf.js/web/viewer.html) is viewable).

Below (scroll down to the bottom of this bug report) is a screenshot depicting what I see when I attemtp to view a downloaded PDF:

**How to reproduce**
1. Open a PDF link, e.g. [this one](http://www.cs.utah.edu/~jmk/kniss_tvcg02-small.pdf).
2. Press <ctrl+p> to open using pdf.js
3. Observe that the result is the one seen in the below screenshot.

**More information**
* OS: Arch Linux, kernel 4.20.12-arch1-1-ARCH. 
* This was not a problem until relatively recently.
* I am not the only person with this bug - see [this Reddit thread](https://www.reddit.com/r/qutebrowser/comments/atipjj/pdfjs_no_longer_working_on_downloaded_files_linux/). The OP is NOT me! I am just relaying some of the information he/she posted here, along with some of my own information.

**Screenshot**
![qutebrowser_pdfjs_broken](https://user-images.githubusercontent.com/5407450/53361494-20350780-38f5-11e9-8a08-02c40f98c590.png)

**Comment by jgkamat** [comment]
n8xm writes:

> **Version info (see `:version`)**: 1.5.2

Can you try 1.6.0? qutebrowser 1.5.2 dosen't support qt 5.12.

**Comment by The-Compiler** [comment]
Likely fixed in v1.6.0, feel free to reopen if not.

**Comment by IvanDelsinne** [comment]
Still happening on Qutebrowser v1.6.3 as of today, using `pdfjs` installed from archlinux.
