### ISSUE TITLE
Unable to login to gmail - This browser or app may not be secure

### ISSUE THREAD

**Issue by Migacz85** [qutebrowser/qutebrowser#5147]
So I'm unable to log in to google services, including gmail, youtube etc. And have this message while trying to login:

This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

version of qutebrowser:
qutebrowser v1.8.3
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.8.0
Qt: 5.13.2
PyQt: 5.13.2

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.3.200 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.3.15-1-MANJARO-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/migacz/.cache/qutebrowser
config: /home/migacz/.config/qutebrowser
data: /home/migacz/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/migacz/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:29

**Comment by The-Compiler** [comment]
Duplicate of #4810

**Comment by The-Compiler** [comment]
Note this affects more than just qutebrowser, see e.g. the [recent Bleeping Computer article](https://www.bleepingcomputer.com/news/google/google-now-bans-some-linux-web-browsers-from-their-services/).

Some more information:

https://lists.schokokeks.org/pipermail/qutebrowser/2019-December/000668.html
https://lists.schokokeks.org/pipermail/qutebrowser/2019-December/000676.html

I can think of a workaround (as part of a #4810), but no idea how long that'll continue working.

**Comment by Migacz85** [comment]
Omg...

**Comment by Al-Caveman** [comment]
that's in goog's english.  if we translate it to the normal english, it means that mr. goog  is asking u to set ur user agent to chromium on windows.

**Comment by The-Compiler** [comment]
@Al-Caveman I'm guessing you don't get this issue with `--temp-basedir` either, since only a subset of all Google accounts are affected (mine aren't either, which makes this hard to test...). According to various reports of affected users, setting a Chromium UA *doesn't* help. However, setting a Firefox UA seems to help, and I plan to push out a workaround (together with some others mentioned in #4810) soon.

**Comment by Al-Caveman** [comment]
@The-Compiler any idea how would goog identify that the request is from qb?

**Comment by The-Compiler** [comment]
@Al-Caveman No idea. Probably it tries to access some Google/Chrome specific JavaScript API if it gets a Chrome user agent.

**Comment by The-Compiler** [comment]
I now pushed a fix for known-broken sites (WhatsApp, Google login, etc.) to the `user-agent` branch. If you're affected by one of those, could you please try that branch without any custom user agent set? Thanks!

**Comment by sid-code** [comment]
Thanks for looking into this.

I'm using a freshly pulled qutebrowser (https://paste.the-compiler.org/view/70168b17), and I'm still having this issue. Setting the user-agent isn't doing anything.

Incidentally, this has given me the ounce of motivation to stop using Google services for personal mail and I've since set up my own mail server, but I thought I'd let you know.

**Comment by The-Compiler** [comment]
@sid-code Please be careful when adding entirely new information to comments by editing them - I often read comments via mail, so I almost missed this.

In 998ccf151505712c873c26aea67e5f7a7c1d3f2f, I decided to set the Firefox UA for the entire `accounts.google.com` subdomain instead - thanks for the report!

**Comment by The-Compiler** [comment]
I just wrote a more detailed explanation for what's going on with the Google Accounts issue: #5182

@Migacz85 I also edited your original post with a link to give this some more visibility. I hope that's okay!

**Comment by Migacz85** [comment]
@The-Compiler This is just great ! So happy that it is fixed now !
