### ISSUE TITLE
Performance impact of global eventfilter

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5376]
> When completely idle, I see that happening around once all 5-10 seconds. Surely that can't be the cause for 20-30% CPU usage, especially when the same is happening in a different codebase as well wink

[out.txt](https://github.com/qutebrowser/qutebrowser/files/4512359/out.txt)

For me at least, I'm getting at least 1000 calls per second on those functions (it's probably actually significantly higher than this, as turning on profiling slows down those calls). And considering each one of these calls is waking up the python interpreter (and the fact that even trivial operations in the interpreter are very slow), I wouldn't be surprised if it made a difference of 5-10% on idle.

_Originally posted by @jgkamat in https://github.com/qutebrowser/qutebrowser/issues/5375#issuecomment-617385703_

**Comment by The-Compiler** [comment]
@jgkamat That's interesting, definitely different from what I'm seeing, and something which *might* be actionable (though I'm not sure if we could get rid of the event filter entirely).

Some questions:

- How are you getting that trace exactly?
- What events are those (can you show the output of `print(obj)` and `print(event.type())` there)?
- What Qt version is this on?
- Can you reproduce this on the latest master and with `--temp-basedir`?

**Comment by The-Compiler** [comment]
I pushed some micro-optimizations in f0948e7e2e39c659c9363c9fac565c3192fd1aaa - even if it getting called so much in idle seems strange; it probably does get called a lot during normal user interaction.

I suppose ideally, we could get rid of the eventFilter completely (or install it in a way it gets called less), though I vaguely remember that not working out a couple of years ago. Possible solutions would be:

- Installing it on individual windows rather than globally (though we still get events to children then?)
- Using QShortcut/QAction instead somehow?
- Using the virtual keyPressEvent on either a QWindow or the QWidget of the main window.

**Comment by jgkamat** [comment]
> because that's not something connected to the website mentioned [...]

That's not entirely true, it's some sites that cause this issue. Not really sure what it is though. Eg: I'm still using https://yourbias.is/ to reproduce this in these tests.

> How are you getting that trace exactly?

with pythonflow using dtrace probes
> What events are those (can you show the output of print(obj) and print(event.type()) there)?

This isn't really helpful, but:
```
<PyQt5.QtCore.QObject object at 0x7f5d244c3828>
1000
```
Here's the full output I get after adding the printouts on (f0948e7).

[printouts.txt](https://github.com/qutebrowser/qutebrowser/files/4512541/printouts.txt)

the `objectName()` seems to be empty string.
The `parent()` seems to be None.

The diff I used was (variations of) http://paste.debian.net/plain/1141958

> What Qt version is this on?
```
qutebrowser v1.10.2
Git commit: f0948e7e2-dirty (2020-04-21 22:20:10 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)
Qt: 5.11.3

CPython: 3.7.3
PyQt: 5.11.3

sip: 4.19.14
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /home/jay/Code/qutebrowser/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-gch9jh6j/cache
config: /tmp/qutebrowser-basedir-gch9jh6j/config
data: /tmp/qutebrowser-basedir-gch9jh6j/data
runtime: /tmp/qutebrowser-basedir-gch9jh6j/runtime

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:01:39
```
> Can you reproduce this on the latest master and with --temp-basedir?

Yes

**Comment by jgkamat** [comment]
With:
```
        print(obj)
        print(obj.objectName())
        print(obj.parent())
        print(event.type())
```

and
```
qutebrowser v1.10.2
Git commit: f0948e7e2-dirty (2020-04-21 22:20:10 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.2
PyQt: 5.14.2

sip: 5.1.2
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform plugin: xcb
Platform: Linux-4.19.0-8-amd64-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /home/jay/Code/qutebrowser/qutebrowser
Using Python from /sbin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-sercfoui/cache
config: /tmp/qutebrowser-basedir-sercfoui/config
data: /tmp/qutebrowser-basedir-sercfoui/data
runtime: /tmp/qutebrowser-basedir-sercfoui/runtime

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:05
```
I still get a bunch of calls on idle, but the output seems a bit different:
```
<PyQt5.QtWidgets.QWidget object at 0x7f178c2f8b80>

<qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f178c2f8160>
12
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtCore.QObject object at 0x7f175059a0d0>

None
1
<PyQt5.QtWidgets.QWidget object at 0x7f178c2f8b80>

<qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f178c2f8160>
1
```

[printout.txt](https://github.com/qutebrowser/qutebrowser/files/4512586/printout.txt)

**Comment by The-Compiler** [comment]
The event types in your Qt 5.11 printout:

```
$ grep '^[0-9]' printouts.txt | sort | uniq -c | sort -nr | head
  10748 1000
   3984 1
   2174 12
   1908 77
    931 43
    450 68
    211 25
    206 24
    184 5
    170 39
```

I do see a lot of 1 (`QTimerEvent`), 77 (`UpdateRequest`) and `12` (`Paint`) as well. You're right that it's probably website-specific, as those (at least `UpdateRequest` and `Paint`) will probably only happen on websites where there's something being repainted all the time.

Type 1000 is `QEvent::User`, i.e. what's supposed to be user-defined events. I do see them with Qt 5.11, but not with Qt 5.12 or newer. Not sure where they're coming from, but apparently it's Qt(WebEngine) generating them somehow, then (at least in older versions).

**Comment by The-Compiler** [comment]
Ah, found it: QtWebEngine used to use it to integrate Chromium's with Qt's event loop (it generated a `UserEvent` in its `base::MessagePump` subclass (`MessagePumpForUIQt`) in `ScheduleWork()`.

With this change in Qt 5.12, it uses a `QTimerEvent` (though also much less, possibly?) instead: [Clean-up BrowserMainPartsQt (I33d9536c) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/243404)

**Comment by toofar** [comment]
I see very low cpu usage for the python process on that site, even with ad blocking disabled and moving the mouse around. I see that maximbaz is using 5.14 too. I'm happy to do more comparative testing if someone tells me what to do:
```
qutebrowser v1.8.1
Git commit: c8974fb1df89-dirty (2020-03-02 20:38:43 +1300)
Backend: QtWebEngine (Chromium 77.0.3865.129)

CPython: 3.8.2
Qt: 5.14.2
PyQt: 5.14.3.dev2004081215

sip: 5.2.0
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.1
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.1.dev2002081012
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform: Linux-5.5.0-16.1-liquorix-amd64-x86_64-with-glibc2.29, 64bit
Linux distribution: Debian GNU/Linux bullseye/sid (debian)
Frozen: False
Imported from /home/user/projects/stable-qutebrowser/qutebrowser
Using Python from /mnt/nvme/user/qt5/build_deb_5.14.2/.venv/bin/python3
Qt library executable path: /usr/local/Qt-5.14.2/libexec, data path: /usr/local/Qt-5.14.2

Paths:
cache: /mnt/ssd/user/qute-basedirs/personal/cache
config: /mnt/ssd/user/qute-basedirs/personal/config
data: /mnt/ssd/user/qute-basedirs/personal/data
runtime: /mnt/ssd/user/qute-basedirs/personal/runtime

Autoconfig loaded: yes
Config.py: /mnt/ssd/user/qute-basedirs/personal/config/config.py has been loaded
Uptime: 2 days, 0:06:05
```

**Comment by The-Compiler** [comment]
@jgkamat Could you give this a try and see how big the difference is in how much the event filter gets called?

```diff
diff --git qutebrowser/keyinput/eventfilter.py qutebrowser/keyinput/eventfilter.py
index 992d9f4ce..9a893265a 100644
--- qutebrowser/keyinput/eventfilter.py
+++ qutebrowser/keyinput/eventfilter.py
@@ -24,7 +24,6 @@ from PyQt5.QtGui import QKeyEvent, QWindow
 from PyQt5.QtWidgets import QApplication
 
 from qutebrowser.keyinput import modeman
-from qutebrowser.misc import quitter
 from qutebrowser.utils import objreg
 
 
@@ -85,11 +84,6 @@ class EventFilter(QObject):
         Return:
             True if the event should be filtered, False if it's passed through.
         """
-        if not isinstance(obj, QWindow):
-            # We already handled this same event at some point earlier, so
-            # we're not interested in it anymore.
-            return False
-
         typ = event.type()
 
         if typ not in self._handlers:
@@ -110,6 +104,4 @@ class EventFilter(QObject):
 
 def init() -> None:
     """Initialize the global EventFilter instance."""
-    event_filter = EventFilter(parent=QApplication.instance())
-    event_filter.install()
-    quitter.instance.shutting_down.connect(event_filter.shutdown)
+    pass
diff --git qutebrowser/mainwindow/mainwindow.py qutebrowser/mainwindow/mainwindow.py
index 03762766d..9b1d81346 100644
--- qutebrowser/mainwindow/mainwindow.py
+++ qutebrowser/mainwindow/mainwindow.py
@@ -36,7 +36,7 @@ from qutebrowser.utils import (message, log, usertypes, qtutils, objreg, utils,
                                jinja, debug)
 from qutebrowser.mainwindow import messageview, prompt
 from qutebrowser.completion import completionwidget, completer
-from qutebrowser.keyinput import modeman
+from qutebrowser.keyinput import modeman, eventfilter
 from qutebrowser.browser import commands, downloadview, hints, downloads
 from qutebrowser.misc import crashsignal, keyhintwidget, sessions
 
@@ -283,6 +283,9 @@ class MainWindow(QWidget):
         self.state_before_fullscreen = self.windowState()
         stylesheet.set_register(self)
 
+        self.event_filter = eventfilter.EventFilter(parent=self)
+        self.installEventFilter(self.event_filter)
+
     def _init_geometry(self, geometry):
         """Initialize the window geometry or load it from disk."""
         if geometry is not None:
```

**Comment by jgkamat** [comment]
Yup, that's a pretty large difference for me, the number of calls (on arch at least) on idle goes down from ~thousands per second to ~hundreds per second. The only calls left on idle are the updateRequest calls (type  77).


[patched.txt](https://github.com/qutebrowser/qutebrowser/files/4517434/patched.txt)
[stock.txt](https://github.com/qutebrowser/qutebrowser/files/4517435/stock.txt)


One issue I saw though is that qb seems to start in insert mode (without actually being in insert mode), and that "escaping out of modes" seems to not work as well. But I'm guessing that's not the focus right now.

**Comment by The-Compiler** [comment]
Yep, that was just a quick hack. I'll need to check how feasible it is to do things that way, but that difference confirms that it's worthwhile to further investigate that possibility.

**Comment by jpalus** [comment]
I suppose it could be the same issue as I'm observing -- simply moving mouse over empty space of any page triggers a lot of cpu usage. I guess qutebrowser listens to mouse movement events even though it does not react to it. Note that it might not be as noticeable on fast x86, but on my ARM laptop simply moving mouse eats more than 2 cores.

Fun fact: simply having this issue opened in qutebrowser, doing nothing, eats 40% cpu. When I type this comment it jumps to 100% in total (whole core). If I open another tab keeping one with this issue in background than cpu usage goes down. Other pages usually don't exhibit such behavior.

**Comment by The-Compiler** [comment]
Did some more tinkering around to see what'd break. The previous issues were because we need the event filters installed on the `RenderWidgetHostViewQt` (aka the `focusProxy` for every tab) too:

```diff
diff --git a/qutebrowser/browser/browsertab.py b/qutebrowser/browser/browsertab.py
index b3d1e85f7..47d2be6fc 100644
--- a/qutebrowser/browser/browsertab.py
+++ b/qutebrowser/browser/browsertab.py
@@ -40,6 +40,7 @@
         QWebEngineHistory, QWebEngineHistoryItem, QWebEnginePage)
 
 from qutebrowser.keyinput import modeman
+from qutebrowser.keyinput import eventfilter as globaleventfilter
 from qutebrowser.config import config
 from qutebrowser.utils import (utils, objreg, usertypes, log, qtutils,
                                urlutils, message, jinja)
@@ -966,6 +967,7 @@ def __init__(self, *, win_id: int,
         self._load_status = usertypes.LoadStatus.none
         self._tab_event_filter = eventfilter.TabEventFilter(
             self, parent=self)
+        self._event_filter = globaleventfilter.EventFilter(parent=self)
         self.backend: Optional[usertypes.Backend] = None
 
         # If true, this tab has been requested to be removed (or is removed).
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index b2ca42cbe..cb53f2cfd 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -1284,6 +1284,7 @@ def _install_event_filter(self):
         fp = self._widget.focusProxy()
         if fp is not None:
             fp.installEventFilter(self._tab_event_filter)
+            fp.installEventFilter(self._event_filter)
 
         self._child_event_filter = eventfilter.ChildEventFilter(
             eventfilter=self._tab_event_filter,
@@ -1291,6 +1292,12 @@ def _install_event_filter(self):
             parent=self)
         self._widget.installEventFilter(self._child_event_filter)
 
+        self._child_event_filter_2 = eventfilter.ChildEventFilter(
+            eventfilter=self._event_filter,
+            widget=self._widget,
+            parent=self)
+        self._widget.installEventFilter(self._child_event_filter_2)
+
     @pyqtSlot()
     def _restore_zoom(self):
         if sip.isdeleted(self._widget):
diff --git a/qutebrowser/keyinput/eventfilter.py b/qutebrowser/keyinput/eventfilter.py
index 4d016bea6..7a9a0d266 100644
--- a/qutebrowser/keyinput/eventfilter.py
+++ b/qutebrowser/keyinput/eventfilter.py
@@ -25,7 +25,7 @@
 from PyQt5.QtGui import QKeyEvent, QWindow
 
 from qutebrowser.keyinput import modeman
-from qutebrowser.misc import quitter, objects
+from qutebrowser.misc import objects
 from qutebrowser.utils import objreg
 
 
@@ -86,11 +86,6 @@ def eventFilter(self, obj: QObject, event: QEvent) -> bool:
         Return:
             True if the event should be filtered, False if it's passed through.
         """
-        if not isinstance(obj, QWindow):
-            # We already handled this same event at some point earlier, so
-            # we're not interested in it anymore.
-            return False
-
         typ = event.type()
 
         if typ not in self._handlers:
@@ -111,6 +106,4 @@ def eventFilter(self, obj: QObject, event: QEvent) -> bool:
 
 def init() -> None:
     """Initialize the global EventFilter instance."""
-    event_filter = EventFilter(parent=objects.qapp)
-    event_filter.install()
-    quitter.instance.shutting_down.connect(event_filter.shutdown)
+    pass
diff --git a/qutebrowser/keyinput/modeman.py b/qutebrowser/keyinput/modeman.py
index 21a6be052..a5640f81e 100644
--- a/qutebrowser/keyinput/modeman.py
+++ b/qutebrowser/keyinput/modeman.py
@@ -78,9 +78,10 @@ class UnavailableError(Exception):
 
 def init(win_id: int, parent: QObject) -> 'ModeManager':
     """Initialize the mode manager and the keyparsers for the given win_id."""
+    log_sensitive_keys = 'log-sensitive-keys' in objects.debug_flags
     commandrunner = runners.CommandRunner(win_id)
 
-    modeman = ModeManager(win_id, parent)
+    modeman = ModeManager(win_id, parent, log_sensitive_keys=log_sensitive_keys)
     objreg.register('mode-manager', modeman, scope='window', window=win_id)
 
     hintmanager = hints.HintManager(win_id, parent=parent)
@@ -88,8 +89,6 @@ def init(win_id: int, parent: QObject) -> 'ModeManager':
                     window=win_id, command_only=True)
     modeman.hintmanager = hintmanager
 
-    log_sensitive_keys = 'log-sensitive-keys' in objects.debug_flags
-
     keyparsers: ParserDictType = {
         usertypes.KeyMode.normal:
             modeparsers.NormalKeyParser(
@@ -257,7 +256,12 @@ class ModeManager(QObject):
     left = pyqtSignal(usertypes.KeyMode, usertypes.KeyMode, int)
     keystring_updated = pyqtSignal(usertypes.KeyMode, str)
 
-    def __init__(self, win_id: int, parent: QObject = None) -> None:
+    def __init__(
+        self,
+        win_id: int,
+        parent: QObject = None, *,
+        log_sensitive_keys: bool = False,
+    ) -> None:
         super().__init__(parent)
         self._win_id = win_id
         self.parsers: ParserDictType = {}
@@ -266,6 +270,7 @@ def __init__(self, win_id: int, parent: QObject = None) -> None:
         self._releaseevents_to_pass: Set[KeyEvent] = set()
         # Set after __init__
         self.hintmanager = cast(hints.HintManager, None)
+        self._log_sensitive_keys = log_sensitive_keys
 
     def __repr__(self) -> str:
         return utils.get_repr(self, mode=self.mode)
@@ -283,7 +288,7 @@ def _handle_keypress(self, event: QKeyEvent, *,
         """
         curmode = self.mode
         parser = self.parsers[curmode]
-        if curmode != usertypes.KeyMode.insert:
+        if self._log_sensitive_keys or curmode != usertypes.KeyMode.insert:
             log.modes.debug("got keypress in mode {} - delegating to {}".format(
                 utils.pyenum_str(curmode), utils.qualname(parser)))
         match = parser.handle(event, dry_run=dry_run)
diff --git a/qutebrowser/mainwindow/mainwindow.py b/qutebrowser/mainwindow/mainwindow.py
index d0723742a..b59f49bb1 100644
--- a/qutebrowser/mainwindow/mainwindow.py
+++ b/qutebrowser/mainwindow/mainwindow.py
@@ -37,7 +37,7 @@
                                jinja, debug)
 from qutebrowser.mainwindow import messageview, prompt
 from qutebrowser.completion import completionwidget, completer
-from qutebrowser.keyinput import modeman
+from qutebrowser.keyinput import modeman, eventfilter
 from qutebrowser.browser import downloadview, hints, downloads
 from qutebrowser.misc import crashsignal, keyhintwidget, sessions, objects
 from qutebrowser.qt import sip
@@ -281,6 +281,9 @@ def __init__(self, *,
         self.state_before_fullscreen = self.windowState()
         stylesheet.set_register(self)
 
+        self.event_filter = eventfilter.EventFilter(parent=self)
+        self.installEventFilter(self.event_filter)
+
     def _init_geometry(self, geometry):
         """Initialize the window geometry or load it from disk."""
         if geometry is not None:

```

This still breaks some stuff, however - curiously enough I don't see the cursor blinking sometimes, for example.

Tests:

```
FAILED tests/end2end/features/test_caret_bdd.py::test_selectionfollow_with_link_tabbing_without_js - end2end.fixtures.testprocess.WaitForTimeout: Timed out while waiting for http://localhost:60279/data/hello.txt to be loaded
FAILED tests/end2end/features/test_caret_bdd.py::test_selectionfollow_with_link_tabbing_with_js - end2end.fixtures.testprocess.WaitForTimeout: Timed out while waiting for http://localhost:60279/data/hello.txt to be loaded
FAILED tests/end2end/features/test_caret_bdd.py::test_selectionfollow_with_link_tabbing_in_a_tab_without_js - end2end.fixtures.testprocess.WaitForTimeout: Timed out while waiting for http://localhost:60279/data/hello.txt to be loaded
FAILED tests/end2end/features/test_caret_bdd.py::test_selectionfollow_with_link_tabbing_in_a_tab_with_js - end2end.fixtures.testprocess.WaitForTimeout: Timed out while waiting for http://localhost:60279/data/hello.txt to be loaded
FAILED tests/end2end/features/test_keyinput_bdd.py::test_fakekey_sending_key_to_the_website - end2end.fixtures.testprocess.WaitForTimeout: Timed out after 5000ms waiting for {'category': 'js', 'message': '[*] key press: 88'}.
FAILED tests/end2end/features/test_keyinput_bdd.py::test_fakekey_sending_special_key_to_the_website - end2end.fixtures.testprocess.WaitForTimeout: Timed out after 5000ms waiting for {'category': 'js', 'message': '[*] key press: 27'}.
FAILED tests/end2end/features/test_keyinput_bdd.py::test_fakekey_sending_keychain_to_the_website - end2end.fixtures.testprocess.WaitForTimeout: Timed out after 5000ms waiting for {'category': 'js', 'message': '[*] key press: 88'}.
```

**Comment by The-Compiler** [comment]
On a second thought, installing on the `RenderWidgetHostViewQt` probably means we get some events (like paint events) again. Wonder if we could indeed use QShortcut/QAction, or the underlying ShotcutOverride event.

**Comment by The-Compiler** [comment]
Another data point: Running [speedometer](https://browserbench.org/Speedometer2.1/) after `:debug-trace` spams the terminal with:

```python
[...]qutebrowser/keyinput/eventfilter.py:65    call      => eventFilter(self=<qutebrowser.keyinput.eventfilter.EventFilter object at 0x7fab4d3ccee0>, obj=<qutebrowser.mainwindow.mainwindow.MainWindow object at 0x7fab4d3ccf70>, event=<PyQt6.QtCore.QEvent object at 0x7fab1c2d2c20>)
[...]qutebrowser/keyinput/eventfilter.py:75    line         assert event is not None
[...]qutebrowser/keyinput/eventfilter.py:76    line         ev_type = event.type()
             /usr/lib/python3.11/enum.py:686   call         => __call__(cls=<enum.EnumType object at 0x56175c286050>, value=77, names=None, module=None, qualname=None, type=None, start=1, boundary=None)
             /usr/lib/python3.11/enum.py:711   line            if names is None:  # simple value lookup
             /usr/lib/python3.11/enum.py:712   line            return cls.__new__(cls, value)
             /usr/lib/python3.11/enum.py:1091  call            => __new__(cls=<enum.EnumType object at 0x56175c286050>, value=77)
             /usr/lib/python3.11/enum.py:1095  line               if type(value) is cls:
             /usr/lib/python3.11/enum.py:1100  line               try:
             /usr/lib/python3.11/enum.py:1101  line               return cls._value2member_map_[value]
             /usr/lib/python3.11/enum.py:1101  return          <= __new__: <PyQt6.QtCore.QEvent.Type object at 0x7fab4ddef200>
             /usr/lib/python3.11/enum.py:712   return       <= __call__: <PyQt6.QtCore.QEvent.Type object at 0x7fab4ddef200>
[...]qutebrowser/keyinput/eventfilter.py:78    line         if self._log_qt_events:
[...]qutebrowser/keyinput/eventfilter.py:88    line         ev_type == QEvent.Type.DragEnter and
[...]qutebrowser/keyinput/eventfilter.py:100   line         if not isinstance(obj, QWindow):
[...]qutebrowser/keyinput/eventfilter.py:103   line         return False
[...]qutebrowser/keyinput/eventfilter.py:103   return    <= eventFilter: False
```
