### ISSUE TITLE
Blank screen loading Centrify MFA login page

### ISSUE THREAD

**Issue by Hylian** [qutebrowser/qutebrowser#5526]
**Version info**:
```
qutebrowser v1.12.0
Git commit: 6d8553af3 (2020-06-13 00:40:08 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: unknown (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.32.2
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
I upgraded my Arch distribution to the latest `qutebrowser-git` and latest Qt, etc., and my organization's SSO/MFA page provided by Idaptive (Centrify) fails to display properly. It just shows a blank grey screen. I've tried messing with the user agent for the page in my `config.py`, but to no avail.

**How to reproduce**
Navigate to: https://google.my.centrify.com/my
(Note: I don't actually work for Google, this is just a page that seems to also be affected, just like my org's.)

P.S. Thank you for building qutebrowser! I've been using it for years, and it's an invaluable tool to me at this point.

**Comment by Hylian** [comment]
Update: I've downgraded the `python-pyqtwebengine` and `qt5-webengine` packages, and that seems to have fixed it.
```
sudo pacman -U /var/cache/pacman/pkg/python-pyqtwebengine-5.14.0-3-x86_64.pkg.tar.xz  
sudo pacman -U /var/cache/pacman/pkg/qt5-webengine-5.14.2-3-x86_64.pkg.tar.zst 
```

**Comment by The-Compiler** [comment]
Probably an issue in Qt 5.15 or the underlying Chromium. The inspector says:

> Uncaught (in promise) DOMException: The user agent does not support public key credentials.

**Comment by The-Compiler** [comment]
Reported upstream: [[QTBUG-85117] [REG 5.15] Centrify login page does not work: The user agent does not support public key credentials. - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-85117)

**Comment by Hylian** [comment]
Updated to `qt5-webengine 5.15.0-5` and the issue is resolved.

**Comment by The-Compiler** [comment]
@Hylian huh, that's weird! I don't see anything in those versions which would have fixed this, and I still see the same isuse with those versions and the google centrify page above.

**Comment by The-Compiler** [comment]
Looks like an upstream fix (probably for Qt 5.15.1) is in progress now: [Fix WebAuth build (If73ce3fc) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/308434)
