### ISSUE TITLE
DevTools Console Autocompletion is Broken

### ISSUE THREAD

**Issue by chaorace** [qutebrowser/qutebrowser#5759]
**Version info**:

```
qutebrowser v1.13.1
Git commit: 14d01ca5e on master (2020-10-01 19:43:28 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```
Full: https://paste.the-compiler.org/view/f8a430fc

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
DevTools console autocompletion only works for top-level objects. I began experiencing this issue a few months ago, but never got around to reporting it. I built the latest git commit and can verify that the issue is still affecting me. Autocompletion works fine for top level objects, but will get stuck at this point and never advance beyond that.

Demonstration Video:
https://gfycat.com/ifr/FearfulSarcasticLeafbird

**How to reproduce**

1. Open any given website, Google will suffice
2. Invoke the DevTools inspector
3. Focus the DevTools console and type `document.`
4. Autocompletion gets stuck and continues to recommend "document"
5. Bonus: Accidentally pressing enter replaces any input you may have provided and replaces it with "document"

**Comment by The-Compiler** [comment]
See [[QTBUG-83729] [Reg 5.14->5.15.0] Completion in the "Console" tab only works for the immediate "window" object properties - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-83729)

It's been fixed in Qt 5.15.1 which has landed in Archlinux almost a month ago - as soon as Manjaro upgrades to that, you'll get the fix as well.

**Comment by chaorace** [comment]
I see, thank you very much for helping me connect the dots!

I went ahead and upgraded to the unstable branch of my distro to get the latest Qt5 and recompiled qutebrowser, but I'm still experiencing the issue, unfortunately. Would you have any further advice?

Updated Version String:
```
qutebrowser v1.13.1
Git commit: ceb6c83ae on master (2020-10-02 09:43:06 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1
```

(Full: https://paste.the-compiler.org/view/e5fefccb)

**Comment by The-Compiler** [comment]
Works fine for me (based on your reproduction steps). Can you check with another QtWebEngine-based browser such as KDE Falkon as well, and if so, open a new bug in the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Comment by chaorace** [comment]
Yep, reproducing on Falkon as well. I've opened a new Jira bug with the QT team under [QTBUG-87129](https://bugreports.qt.io/browse/QTBUG-87129).

Thank you again for the fantastic support, I use qutebrowser every day and absolutely love the experience!

**Comment by The-Compiler** [comment]
Ah, I see the QtWebEngine change links the following commits:

- [Build devtools modules with system nodejs (Ied0c8d9a) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/298887)
- [Detect the presence of host node.js (I88d784e3) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/305160)

So maybe this is a Manjaro packaging bug and they're missing nodejs?

**Comment by chaorace** [comment]
Possibly? To test that theory I went ahead and manually installed the arch repo release of the qt5-webengine package, but I'm seeing no change in behavior after doing so. Not sure what else I can do to verify, should I try building qt5-webengine myself?

**Comment by The-Compiler** [comment]
I assume you're still trying with the same reproducer you've described in the original post, with `document.` on Google?

**Comment by chaorace** [comment]
Correct, though I can verify multiple other sites are affected

**Comment by The-Compiler** [comment]
Ah, I actually have my own `qt5-webengine-debug` package installed, which happened to pick up my system-wide node (I don't build in isolated environments because I didn't get around to setting them up yet...).

Thus, this is an Archlinux packaging bug - I opened a report here: [FS#68075 : [qt5-webengine] Missing node makdepends for devtools autocompletion](https://bugs.archlinux.org/task/68075)

**Comment by chaorace** [comment]
Awesome, thanks for helping out with putting the report in for the faulty package. I wonder if any other distributions are affected by the same issue? I checked the [Ubuntu packages](https://packages.ubuntu.com/groovy/libqt5webengine5) on a whim and it _seems_ like they're also missing the node dependency.

Then again, it's not like I'm going to install a VM and test dependencies all day! I suppose people will just have to report to package maintainers as this bug slowly pops up in various odd places.

**Comment by The-Compiler** [comment]
It's a new thing in Qt 5.15.1, so those Ubuntu packages aren't relevant. But yes, with other distributions adopting Qt 5.15 and this being a rather subtle change without a changelog entry, it seems likely that it'll pop up in other places as well.

**Comment by The-Compiler** [comment]
Looks like Archlinux has already uploaded a fixed qt5-webengine 5.15.1-3 :slightly_smiling_face:

**Comment by chaorace** [comment]
Just loaded up the latest arch package, **it works!**
