### ISSUE TITLE
crash on suspend/resume

### ISSUE THREAD

**Issue by mikezackles** [qutebrowser/qutebrowser#8651]
**Version info**:
qutebrowser v3.5.1
Git commit: 
Backend: QtWebEngine 6.9.1
  based on Chromium 130.0.6723.192
  with security patches up to 136.0.7103.114 (plus any distribution patches)
  (source: api)
Qt: 6.9.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
qutebrowser crashes after suspend/resume using swaywm on Arch

**How to reproduce**
* open a site using GL in qutebrowser (openstreetmap.org works for me)
* suspend & resume

Backtrace: (doesn't find a current screen info)
```
#0  0x00007fffea6dc5e1 in base::ImmediateCrash () at ../../../../../qtwebengine/src/3rdparty/chromium/base/immediate_crash.h:176
#1  logging::CheckFailure () at ../../../../../qtwebengine/src/3rdparty/chromium/base/check.h:213
#2  display::ScreenInfos::current () at ./../../../../../qtwebengine/src/3rdparty/chromium/ui/display/screen_infos.cc:38
#3  display::ScreenInfos::mutable_current () at ./../../../../../qtwebengine/src/3rdparty/chromium/ui/display/screen_infos.cc:29
#4  0x00007fffe481f6b6 in QtWebEngineCore::RenderWidgetHostViewQt::updateScreenInfo () at /usr/src/debug/qt6-webengine/qtwebengine/src/core/render_widget_host_view_qt.cpp:881
#5  0x00007fffe4824434 in QtWebEngineCore::RenderWidgetHostViewQtDelegateClient::visualPropertiesChanged () at /usr/src/debug/qt6-webengine/qtwebengine/src/core/render_widget_host_view_qt_delegate_client.cpp:222
#6  0x00007fffe402be42 in QQuickItemPrivate::itemChange (this=<optimized out>, change=QQuickItem::ItemDevicePixelRatioHasChanged, data=...) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickitem.cpp:6964
#7  updatePixelRatioHelper (item=0x5555573de800, pixelRatio=pixelRatio@entry=1.5) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:387
#8  0x00007fffe402bda1 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=1.5) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:392
#9  0x00007fffe402bda1 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=1.5) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:392
#10 0x00007fffe4033558 in QQuickWindow::physicalDpiChanged (this=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:403
#11 0x00007fffe40368fd in QQuickWindow::event (this=<optimized out>, event=<optimized out>) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:1614
#12 0x00007ffff2bb6c70 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#13 0x00007ffff34c4c37 in sipQApplication::notify (this=0x555555c44e50, a0=0x5555573d6520, a1=0x7fffffffd530) at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:249
#14 0x00007ffff6366118 in QCoreApplication::notifyInternal2 (receiver=0x5555573d6520, event=0x7fffffffd530) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#15 0x00007ffff23c6e52 in QWindowPrivate::updateDevicePixelRatio() () from /usr/lib/libQt6Gui.so.6
#16 0x00007ffff63d17ef in QtPrivate::QSlotObjectBase::call (this=<optimized out>, r=<optimized out>, a=<optimized out>, this=<optimized out>, r=<optimized out>, a=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs_impl.h:461
#17 doActivate<false> (sender=<optimized out>, signal_index=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:4146
#18 0x00007ffff23bd631 in QWindowPrivate::setTopLevelScreen(QScreen*, bool) () from /usr/lib/libQt6Gui.so.6
#19 0x00007ffff23d800a in QWindowSystemInterface::handleScreenRemoved(QPlatformScreen*) () from /usr/lib/libQt6Gui.so.6
#20 0x00007fffd26e7f84 in QtWaylandClient::QWaylandDisplay::registry_global_remove (this=0x555555f07bf0, id=67) at /usr/src/debug/qt6-wayland/qtwayland/src/client/qwaylanddisplay.cpp:842
#21 0x00007ffff0222ac6 in ?? () from /usr/lib/libffi.so.8
#22 0x00007ffff021f76b in ?? () from /usr/lib/libffi.so.8
#23 0x00007ffff022206e in ffi_call () from /usr/lib/libffi.so.8
#24 0x00007ffff6bed910 in wl_closure_invoke (closure=closure@entry=0x7fffcc003350, target=<optimized out>, target@entry=0x555555f0e240, opcode=opcode@entry=1, data=<optimized out>, flags=1) at ../wayland-1.23.1/src/connection.c:1228
#25 0x00007ffff6bee199 in dispatch_event (display=display@entry=0x555555dbf350, queue=queue@entry=0x555555dbf448) at ../wayland-1.23.1/src/wayland-client.c:1674
#26 0x00007ffff6bee573 in dispatch_queue (display=0x555555dbf350, queue=0x555555dbf448) at ../wayland-1.23.1/src/wayland-client.c:1820
#27 wl_display_dispatch_queue_pending (display=0x555555dbf350, queue=0x555555dbf448) at ../wayland-1.23.1/src/wayland-client.c:2062
#28 0x00007fffd26e4266 in QtWaylandClient::QWaylandDisplay::flushRequests (this=<optimized out>) at /usr/src/debug/qt6-wayland/qtwayland/src/client/qwaylanddisplay.cpp:228
#29 0x00007ffff63bee34 in QObject::event (this=<optimized out>, e=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:1431
#30 0x00007ffff2bb6c70 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#31 0x00007ffff34c4c37 in sipQApplication::notify (this=0x555555c44e50, a0=0x555555f07bf0, a1=0x7fffcc002cd0) at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:249
#32 0x00007ffff6366118 in QCoreApplication::notifyInternal2 (receiver=0x555555f07bf0, event=event@entry=0x7fffcc002cd0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#33 0x00007ffff63664fb in QCoreApplication::sendEvent (receiver=<optimized out>, event=0x7fffcc002cd0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1546
#34 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x55555571b5a0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1879
#35 0x00007ffff663dcf8 in QCoreApplication::sendPostedEvents (receiver=0x0, event_type=0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1733
#36 postEventSourceDispatch (s=0x555555f036d0) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:246
#37 0x00007ffff58f387d in ?? () from /usr/lib/libglib-2.0.so.0
#38 0x00007ffff58f4cd7 in ?? () from /usr/lib/libglib-2.0.so.0
#39 0x00007ffff58f4ee5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#40 0x00007ffff663a5e2 in QEventDispatcherGlib::processEvents (this=0x555555ae31c0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#41 0x00007ffff63724b6 in QEventLoop::processEvents (this=0x7fffffffe190, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:104
#42 QEventLoop::exec (this=0x7fffffffe190, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:186
#43 0x00007ffff636a7c1 in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1449
#44 0x00007ffff34c10ac in meth_QApplication_exec (sipSelf=<optimized out>, sipArgs=<optimized out>) at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:1289
#45 0x00007ffff7b990eb in ?? () from /usr/lib/libpython3.13.so.1.0
#46 0x00007ffff7b6446b in _PyObject_MakeTpCall () from /usr/lib/libpython3.13.so.1.0
#47 0x00007ffff7b75cd4 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.13.so.1.0
#48 0x00007ffff7c48695 in PyEval_EvalCode () from /usr/lib/libpython3.13.so.1.0
#49 0x00007ffff7c86433 in ?? () from /usr/lib/libpython3.13.so.1.0
#50 0x00007ffff7c8381a in ?? () from /usr/lib/libpython3.13.so.1.0
#51 0x00007ffff7c80f27 in ?? () from /usr/lib/libpython3.13.so.1.0
#52 0x00007ffff7c801e0 in ?? () from /usr/lib/libpython3.13.so.1.0
#53 0x00007ffff7c7fff3 in ?? () from /usr/lib/libpython3.13.so.1.0
#54 0x00007ffff7c7e244 in Py_RunMain () from /usr/lib/libpython3.13.so.1.0
#55 0x00007ffff7c3595c in Py_BytesMain () from /usr/lib/libpython3.13.so.1.0
#56 0x00007ffff783e6b5 in __libc_start_call_main (main=main@entry=0x555555555120, argc=argc@entry=3, argv=argv@entry=0x7fffffffe9a8) at ../sysdeps/nptl/libc_start_call_main.h:58
#57 0x00007ffff783e769 in __libc_start_main_impl (main=0x555555555120, argc=3, argv=0x7fffffffe9a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe998) at ../csu/libc-start.c:360
#58 0x0000555555555045 in _start ()
```

This has been happening consistently since Qt 6.9 landed

**Comment by The-Compiler** [comment]
Qt issue which is already fixed, should be in Qt 6.9.2: [[QTBUG-136481] QtWebEngine crashes when screen is removed - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-136481)

**Comment by akrameh** [comment]
> Qt issue which is already fixed, should be in Qt 6.9.2: [[QTBUG-136481] QtWebEngine crashes when screen is removed - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-136481)

hey this issue seem that it been closed on qtwebengine but it still happens to me on swaywm, when i close lid and let it set for few minuts then reopen, qutebrowser window will be closed i need to reopen qutebrowser for my tabs to show up again

**Comment by The-Compiler** [comment]
Qt 6.9.2 [hasn't been released yet](https://wiki.qt.io/Qt_6.9_Release).

**Comment by mikezackles** [comment]
Arch is shipping 6.9.2 now, and I can confirm that the issue is resolved.

**Comment by mikezackles** [comment]
I spoke too soon. This is still happening with qt 6.9.2, but slightly less frequently. I know it's likely an upstream issue, but it makes using qutebrowser on swaywm quite painful.

I've updated the upstream bug as well.

```
#0  0x00007fffea63a361 in base::ImmediateCrash () at ../../../../../qtwebengine/src/3rdparty/chromium/base/immediate_crash.h:176
#1  logging::CheckFailure () at ../../../../../qtwebengine/src/3rdparty/chromium/base/check.h:213
#2  display::ScreenInfos::current () at ./../../../../../qtwebengine/src/3rdparty/chromium/ui/display/screen_infos.cc:38
#3  display::ScreenInfos::mutable_current () at ./../../../../../qtwebengine/src/3rdparty/chromium/ui/display/screen_infos.cc:29
#4  0x00007fffe476a5d6 in QtWebEngineCore::RenderWidgetHostViewQt::updateScreenInfo ()
    at /usr/src/debug/qt6-webengine/qtwebengine/src/core/render_widget_host_view_qt.cpp:883
#5  0x00007fffe476f354 in QtWebEngineCore::RenderWidgetHostViewQtDelegateClient::visualPropertiesChanged ()
    at /usr/src/debug/qt6-webengine/qtwebengine/src/core/render_widget_host_view_qt_delegate_client.cpp:222
#6  0x00007fffe3f75462 in QQuickItemPrivate::itemChange (this=<optimized out>, change=QQuickItem::ItemDevicePixelRatioHasChanged, 
    data=...) at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickitem.cpp:6967
#7  updatePixelRatioHelper (item=0x555556f6e1b0, pixelRatio=pixelRatio@entry=1.5)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:387
#8  0x00007fffe3f753c1 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=pixelRatio@entry=1.5)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:392
#9  0x00007fffe3f753c1 in updatePixelRatioHelper (item=<optimized out>, pixelRatio=1.5)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:392
#10 0x00007fffe3f7cc58 in QQuickWindow::physicalDpiChanged (this=<optimized out>)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:403
#11 0x00007fffe3f8017d in QQuickWindow::event (this=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-declarative/qtdeclarative/src/quick/items/qquickwindow.cpp:1614
#12 0x00007ffff2b3fdd0 in QApplicationPrivate::notify_helper (this=this@entry=0x7fffffffd3b0, receiver=0x555557d8f980, 
    e=0x7fffffffd560) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3300
#13 0x00007ffff2b43103 in QApplication::notify (this=this@entry=0x555555bc3a60, receiver=receiver@entry=0x555557d8f980, 
    e=e@entry=0x7fffffffd560) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3061
#14 0x00007ffff3451af7 in sipQApplication::notify (this=0x555555bc3a60, a0=0x555557d8f980, a1=0x7fffffffd560)
    at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:249
#15 0x00007ffff62f2678 in QCoreApplication::notifyInternal2 (receiver=0x555557d8f980, event=0x7fffffffd560)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#16 0x00007ffff62f26bd in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1546
#17 0x00007ffff234ff52 in QWindowPrivate::updateDevicePixelRatio (this=0x555557ca9880)
    at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindow.cpp:1440
#18 0x00007ffff635e66f in QtPrivate::QSlotObjectBase::call (this=<optimized out>, r=<optimized out>, a=<optimized out>, 
    this=<optimized out>, r=<optimized out>, a=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs_impl.h:461
#19 doActivate<false> (sender=<optimized out>, signal_index=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:4157
#20 0x00007ffff2346731 in QMetaObject::activate<void, QScreen*> (sender=<optimized out>, mo=<optimized out>, 
    local_signal_index=<optimized out>, ret=<optimized out>, sender=<optimized out>, mo=<optimized out>, 
    local_signal_index=<optimized out>, ret=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs.h:306
#21 QWindow::screenChanged (this=0x555557d8f980, _t1=0x555558d62af0)
    at /usr/src/debug/qt6-base/build/src/gui/Gui_autogen/include/moc_qwindow.cpp:574
#22 QWindowPrivate::emitScreenChangedRecursion (this=0x555557ca9880, newScreen=0x555558d62af0)
    at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindow.cpp:510
#23 QWindowPrivate::setTopLevelScreen (this=0x555557ca9880, newScreen=0x555558d62af0, recreate=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindow.cpp:534
#24 0x00007ffff236120a in QWindow::setScreen (this=0x555557d8f980, newScreen=0x555558d62af0)
    at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindow.cpp:2266
#25 QWindowSystemInterface::handleScreenRemoved (platformScreen=0x555555ec9c20)
    at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindowsysteminterface.cpp:773
#26 0x00007fffd253af04 in QtWaylandClient::QWaylandDisplay::registry_global_remove (this=0x555555ecec70, id=82)
    at /usr/src/debug/qt6-wayland/qtwayland/src/client/qwaylanddisplay.cpp:830
#27 0x00007ffff0199ac6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#28 0x00007ffff019676b in ffi_call_int (cif=cif@entry=0x7fffffffda60, 
    fn=fn@entry=0x7fffd2572760 <QtWayland::wl_registry::handle_global_remove(void*, wl_registry*, unsigned int)>, 
    rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffdb30, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:676
#29 0x00007ffff019906e in ffi_call (cif=cif@entry=0x7fffffffda60, 
    fn=0x7fffd2572760 <QtWayland::wl_registry::handle_global_remove(void*, wl_registry*, unsigned int)>, rvalue=rvalue@entry=0x0, 
    avalue=avalue@entry=0x7fffffffdb30) at ../src/x86/ffi64.c:713
#30 0x00007ffff6b7f48d in wl_closure_invoke (closure=closure@entry=0x7fffcc004870, target=<optimized out>, 
    target@entry=0x555555d5e2c0, opcode=opcode@entry=1, data=<optimized out>, flags=1) at ../wayland-1.24.0/src/connection.c:1241
#31 0x00007ffff6b802e9 in dispatch_event (display=display@entry=0x555555bc1ec0, queue=queue@entry=0x555555bc1fb8)
    at ../wayland-1.24.0/src/wayland-client.c:1707
#32 0x00007ffff6b806f3 in dispatch_queue (display=0x555555bc1ec0, queue=0x555555bc1fb8)
    at ../wayland-1.24.0/src/wayland-client.c:1853
#33 wl_display_dispatch_queue_pending (display=0x555555bc1ec0, queue=0x555555bc1fb8) at ../wayland-1.24.0/src/wayland-client.c:2190
#34 0x00007fffd2537536 in QtWaylandClient::QWaylandDisplay::flushRequests (this=<optimized out>)
    at /usr/src/debug/qt6-wayland/qtwayland/src/client/qwaylanddisplay.cpp:228
#35 0x00007ffff634ba74 in QObject::event (this=<optimized out>, e=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:1432
#36 0x00007ffff2b3fdd0 in QApplicationPrivate::notify_helper (this=this@entry=0x7fffffffdcf0, receiver=0x555555ecec70, 
    e=0x7fffcc004ab0) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3300
#37 0x00007ffff2b43103 in QApplication::notify (this=this@entry=0x555555bc3a60, receiver=receiver@entry=0x555555ecec70, 
    e=e@entry=0x7fffcc004ab0) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3061
#38 0x00007ffff3451af7 in sipQApplication::notify (this=0x555555bc3a60, a0=0x555555ecec70, a1=0x7fffcc004ab0)
    at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:249
#39 0x00007ffff62f2678 in QCoreApplication::notifyInternal2 (receiver=0x555555ecec70, event=event@entry=0x7fffcc004ab0)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1106
#40 0x00007ffff62f2a5b in QCoreApplication::sendEvent (receiver=<optimized out>, event=0x7fffcc004ab0)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1546
#41 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x555555667cb0)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1891
#42 0x00007ffff65cd7f8 in QCoreApplication::sendPostedEvents (receiver=0x0, event_type=0)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1744
#43 postEventSourceDispatch (s=0x555555bc3b30) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:246
#44 0x00007ffff587f880 in g_main_dispatch (context=0x555555bb4860) at ../glib/glib/gmain.c:3398
#45 0x00007ffff5880cd7 in g_main_context_dispatch_unlocked (context=0x555555bb4860) at ../glib/glib/gmain.c:4249
#46 g_main_context_iterate_unlocked (context=context@entry=0x555555bb4860, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at ../glib/glib/gmain.c:4314
#47 0x00007ffff5880ee5 in g_main_context_iteration (context=0x555555bb4860, may_block=1) at ../glib/glib/gmain.c:4379
#48 0x00007ffff65c9fe2 in QEventDispatcherGlib::processEvents (this=0x555555aaaaa0, flags=...)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:399
#49 0x00007ffff62feca6 in QEventLoop::processEvents (this=0x7fffffffe1c0, flags=...)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:104
#50 QEventLoop::exec (this=0x7fffffffe1c0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:186
#51 0x00007ffff62f6d21 in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1449
#52 0x00007ffff2b3a5ea in QApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2567
#53 0x00007ffff344df4c in meth_QApplication_exec (sipSelf=<optimized out>, sipArgs=<optimized out>)
    at /usr/src/debug/pyqt6/pyqt6-6.9.1/build/QtWidgets/sipQtWidgetsQApplication.cpp:1289
#54 0x00007ffff7b89213 in cfunction_call (func=0x7fffd28351c0, args=0x7ffff7ef6548 <_PyRuntime+88296>, kwargs=0x0)
    at Objects/methodobject.c:550
#55 0x00007ffff7b550cb in _PyObject_MakeTpCall (tstate=0x7ffff7f25df0 <_PyRuntime+283024>, callable=0x7fffd28351c0, 
    args=0x7ffff7fad210, nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:242
#56 0x00007ffff7b6997a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>)
    at Python/generated_cases.c.h:813
#57 0x00007ffff7c412c9 in PyEval_EvalCode (co=0x5555556029f0, globals=<optimized out>, locals=0x7ffff71b41c0) at Python/ceval.c:604
#58 0x00007ffff7c7f88c in run_eval_code_obj (tstate=tstate@entry=0x7ffff7f25df0 <_PyRuntime+283024>, co=co@entry=0x5555556029f0, 
    globals=globals@entry=0x7ffff71b41c0, locals=locals@entry=0x7ffff71b41c0) at Python/pythonrun.c:1381
#59 0x00007ffff7c7c85d in run_mod (mod=mod@entry=0x55555561b008, filename=filename@entry=0x7ffff71b4330, 
    globals=globals@entry=0x7ffff71b41c0, locals=locals@entry=0x7ffff71b41c0, flags=flags@entry=0x7fffffffe758, 
    arena=arena@entry=0x7ffff72ffd10, interactive_src=0x0, generate_new_source=0) at Python/pythonrun.c:1466
#60 0x00007ffff7c79f58 in pyrun_file (fp=fp@entry=0x555555570290, filename=filename@entry=0x7ffff71b4330, start=start@entry=257, 
    globals=globals@entry=0x7ffff71b41c0, locals=locals@entry=0x7ffff71b41c0, closeit=closeit@entry=1, flags=0x7fffffffe758)
    at Python/pythonrun.c:1295
#61 0x00007ffff7c79212 in _PyRun_SimpleFileObject (fp=fp@entry=0x555555570290, filename=filename@entry=0x7ffff71b4330, 
    closeit=closeit@entry=1, flags=flags@entry=0x7fffffffe758) at Python/pythonrun.c:517
#62 0x00007ffff7c78b83 in _PyRun_AnyFileObject (fp=fp@entry=0x555555570290, filename=filename@entry=0x7ffff71b4330, 
    closeit=closeit@entry=1, flags=flags@entry=0x7fffffffe758) at Python/pythonrun.c:77
#63 0x00007ffff7c76e51 in pymain_run_file_obj (program_name=0x7ffff720db70, filename=0x7ffff71b4330, skip_source_first_line=0)
    at Modules/main.c:410
#64 pymain_run_file (config=0x7ffff7ef84e8 <_PyRuntime+96392>) at Modules/main.c:429
#65 pymain_run_python (exitcode=0x7fffffffe74c) at Modules/main.c:696
#66 Py_RunMain () at Modules/main.c:775
#67 0x00007ffff7c2ebeb in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:829
#68 0x00007ffff7807675 in __libc_start_call_main (main=main@entry=0x555555555120 <main>, argc=argc@entry=2, 
    argv=argv@entry=0x7fffffffe9b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#69 0x00007ffff7807729 in __libc_start_main_impl (main=0x555555555120 <main>, argc=2, argv=0x7fffffffe9b8, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe9a8) at ../csu/libc-start.c:360
#70 0x0000555555555045 in _start ()
```
